import { Navbar } from '@/Components/Navbar'
import { Homgrid } from '@/Components/Homgrid'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sharecode.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Homgrid />
    </>
  )
}
